springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs

server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    app:
      url: ${PETSTOREAPP_URL:http://localhost:8080}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    orderreservationfn:
      url: ${ORDERRESERVATIONFN_URL:http://localhost:8071/api/OrderItemsReserver}
  cosmosdb:
    database:
      name: petstore-eastus-cosmosdb-db
    container:
      name: order
    account:
      host: ${COSMOSDB_ACCOUNT_HOST}
      key: ${COSMOSDB_ACCOUNT_KEY}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY}
  service-bus:
    connection-string: ${SERVICE_BUS_CONNECTION_STRING}
    queue-name: ${SERVICE_BUS_QUEUE_NAME}
